export enum GeneTypes {
    LIFESPAN_GENE,

    SPEED_GENE,
    VISION_GENE,
    HUNGER_MAX_GENE,
    THIRST_MAX_GENE,
    DIET_SHIFT_GENE,

    GROWTH_RATE_GENE,
    NUTRITIONAL_VALUE_MAX_GENE,
    RARE_PLANT_GENE,
    VENOMOUS_PLANT_GENE
}